### ISSUE TITLE
What is "Column layout" supposed to do ?

### ISSUE THREAD

**Issue by Elaws** [phibr0/obsidian-advanced-toolbar#41]
On iPad, nothing changes when I activate this option (with Toolbar Row Count set to 1 or 2).

Could you please show screenshots of what it is supposed to do and what is the advantage ?

Thanks

**Comment by phibr0** [comment]
Instead of showing Commands from left to right, it shows you commands from top to bottom, switching to the next column after your row count. This makes it a bit easier to sort your Commands in the mobile settings panel

![Screenshot 2022-10-20 at 19 48 29](https://user-images.githubusercontent.com/59741989/197021471-e0e035d9-d817-4db0-9377-f01215642655.png)

**Comment by Elaws** [comment]
Got it, thanks for the explanation
